export const CHANGE_USERINFO = 'change_userInfo'
export const LOGIN = 'login'
export const CHANGE_LOGIN_ICON = 'change_login_icon'
export const CHANGE_MESSAGE = 'change_message'
export const CLEAR_TEXT_INPUT = 'clear_text_input'
